# Generated by Django 5.0.6 on 2024-06-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_post_category_categorytranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='show_image',
            field=models.BooleanField(default=False, verbose_name='Show Image'),
        ),
    ]
